# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
